# Generated by Django 3.1.3 on 2021-10-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('phone', models.IntegerField(null=True, verbose_name='Age')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
    ]
