# Generated by Django 3.1.3 on 2021-10-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
