# Generated by Django 3.1.3 on 2021-10-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20211012_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('password', models.CharField(default='*******', max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
