# Generated by Django 3.1.3 on 2021-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_auto_20211013_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='Date Of Birth'),
        ),
    ]
