# Generated by Django 3.1.3 on 2021-10-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_register_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date Of Birth'),
        ),
    ]
