# Generated by Django 3.1.3 on 2021-10-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_auto_20211014_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='register',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified'),
        ),
    ]
