# Generated by Django 3.1.3 on 2021-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_auto_20211014_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(0, 'Ordinary'), (1, 'SuperHero')], max_length=1, null=True, verbose_name='User Type'),
        ),
    ]
