# Generated by Django 3.1.3 on 2021-10-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_register_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Ordinary'), (1, 'SuperHero')], max_length=1, null=True, verbose_name='User Type'),
        ),
    ]
