# Generated by Django 3.1.3 on 2021-10-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0012_register_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.register', verbose_name='Login'),
        ),
    ]
