# Generated by Django 3.1.3 on 2021-10-26 19:12

from django.db import migrations, models
import django.db.models.deletion
import tutors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0013_login_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price ($)')),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='login',
        ),
        migrations.RemoveField(
            model_name='register',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='register',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=tutors.models.upload_to, verbose_name='Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.product', verbose_name='Product')),
            ],
        ),
    ]
