# Generated by Django 3.1.3 on 2021-10-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_connection',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_seniority',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Image'),
        ),
    ]
