# Generated by Django 3.1.3 on 2021-10-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0017_auto_20211030_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Ordinary'), (1, 'SuperHero')], null=True, verbose_name='User Type'),
        ),
    ]
