# Generated by Django 3.1.3 on 2021-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0018_auto_20211031_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
