# Generated by Django 3.1.3 on 2021-11-11 21:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0019_auto_20211031_1003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
